- name: Configure web server
  hosts: all
  remote_user: ubuntu
  become: yes

  tasks:
    - name: Create a non root user
      user:
        name: johnd
        state: present
    - name: Install nginx
      apt:
        name: nginx
        state: present
    - name: Make sure nginx is running
      systemd:
        name: nginx
        state: started